### PR TITLE
Items

### PR DESCRIPTION
**Pull request by nrmurphy75**
Item branch review for in-game Sprint 2 item implementations.

### CODE REVIEW

**Review by EthanHuston — COMMENTED** [review]
Ethan Huston
9/27/2020
Sprint 2
MapSprite.cs and Map.cs
Nathan Murphy
5 minutes
When item pick up is implemented, since the location variables will be held elsewhere, this class should be able to adapt to this change well since the change may not be applied within these classes.

**Comment by chris101112** [comment]
Chris Lenart
9/27/20
Sprint 2
Arrow.cs and ArrowSprite.cs
Nathan Murphy
10 min
Looks good! Just remove empty spaces in ArrowSprite.cs to clean it up.

**Comment by ryanstuckey0** [comment]
Ryan Stuckey
9/27/2020
Sprint 2
Bomb.cs, BombSprite.cs
10 minutes
Readability is good. Maybe move Sprint2.itemX and Sprint2.itemY into the constants.cs file so they're all in one place.
Line 26: sprite.Width is in the Rectangle constructor class

**Comment by saumyah** [comment]
Saumyah Patel
9/27/2020
Sprint Dos
Fairy.cs and FairySprite.cs
Nathan Murphy
Good implementation of random movement, but using too many lines of code to declare and define instance variables. Delete empty spaces and you'll be fine.

**Review by EthanHuston — COMMENTED** [review]
Ethan Huston
9/27/2020
Sprint 2
TriforceSprite.cs and Triforce.cs
Nathan Murphy
5 minutes
Good implementation, similar to other items this should pair well with later collision detection
However, you used sprite.Width twice instead of sprite.height. Need to fix that.

**Comment by ryanstuckey0** [comment]
Ryan Stuckey
9/27/2020
Sprint 2
Bow.cs, BowSprite.cs
10 minutes
BowSprite.cs:26- you have sprite.Width for both fields in the Rectangle constructor.
Bow.cs:25- Use constants.cs class instead
Readability: good

**Comment by chris101112** [comment]
Chris Lenart
9/27/2020
Sprite 2
Boomerang.cs and BoomerangSprite.cs
Nathan Murphy
10 minutes
BoomerangSprite.cs(Line 26): used sprite.Width for both parameters in the Rectangle() method
Readability is good.

**Comment by saumyah** [comment]
Saumyah Patel
9/27/2020
Sprint Zwei
HeartContainer.cs HeartContainerSprite.cs HeartSprite.cs Heart.cs
Nathan Murphy
HeartContainerSprite.cs for destination rectangle, you had width twice instead of width and height.  Same with HeartSprite.cs.
Delete empty spaces and you're good

**Comment by ryanstuckey0** [comment]
Ryan Stuckey
9/27/2020
Sprite 2
Clock.cs, ClockSprite.cs
10 minutes
Nathan Murphy
ClockSprite.cs:26- Rectangle constructor uses sprite.Width twice
Readability: Good

**Comment by saumyah** [comment]
Saumyah Patel
9/27/2020
Sprint Two
Key.cs KeySprite.cs
Nathan Murphy
KeySprite.cs.cs for destination rectangle, you had width twice instead of width and height. Otherwise, you're good.

**Comment by ryanstuckey0** [comment]
Ryan Stuckey
9/27/2020
Sprite 2
Rupee.cs, RupeeSprite.cs
10 minutes
Nathan Murphy
RupeeSprite.cs:32 - Use constant for number of buffer frames
Rupee.cs:25- Move Sprint2.itemX and Sprint2.itemY to constants class
Readability is good

**Pull request merged**
